-- GENERATED FILE — do not edit by hand. Run `npm run seed:sql`.
-- Seeds the 25 launch artist-era entries from src/data/seedArtists.js.

INSERT INTO artist_dna (
  artist_name, era_label, era_start, era_end, region,
  bpm_min, bpm_max, key_preference, feel,
  percussion_dna, low_end_dna, lead_dna, arrangement_dna,
  energy_dna, room_dna, avoid_list, anchor_tokens, display_order
) VALUES
('Jadakiss',
  'Kiss tha Game Goodbye era (2001-2005)',
  2001,
  2005,
  'Yonkers, New York',
  88,
  98,
  'D minor',
  'grimy NY street rap with triumphant menace',
  ARRAY['snare cracks hard and dry, dead center, zero reverb tail', 'kick stomps flat-footed on the grid, no bounce', 'hats ride straight eighths, thin and metallic']::TEXT[],
  ARRAY['bass sits low and blunt, single sustained notes under the loop', 'sub presence felt in the chest, never melodic']::TEXT[],
  ARRAY['sinister two-note string stab repeating like a threat', 'clipped piano plink circling one dark chord', 'siren-adjacent synth whine buried in the mix']::TEXT[],
  ARRAY['beat drops out for the punchline then slams back', 'loop runs unchanged, tension from repetition']::TEXT[],
  ARRAY['gravel-voiced confrontation energy', 'victory-lap arrogance over hard concrete']::TEXT[],
  ARRAY['parking-garage concrete slap', 'close and airless mix']::TEXT[],
  ARRAY['melodic hooks', 'bright synths', 'sung vocals']::TEXT[],
  ARRAY['gritty Yonkers street rap', 'early-2000s NY hardcore hip hop']::TEXT[],
  1),
('Nas',
  'Illmatic era (1993-1995)',
  1993,
  1995,
  'Queensbridge, New York',
  86,
  94,
  'C minor',
  'dusty jazz-loop boom bap, documentary street poetry',
  ARRAY['cracked snare lands square on the two and four, paper-dry', 'kick thuds soft-edged and dusty like a worn drum break', 'ride cymbal shimmer looped from old vinyl, hiss intact']::TEXT[],
  ARRAY['upright-style bassline walks slow and dry beneath the loop', 'low end lean and woody, never boosted']::TEXT[],
  ARRAY['melancholy piano loop drifting through minor changes', 'muted trumpet-shaped phrase smeared by vinyl dust', 'thin high string pad hanging like fog']::TEXT[],
  ARRAY['one loop carried the whole song, filtered for verses', 'scratched vocal hook on the chorus']::TEXT[],
  ARRAY['wise-beyond-years calm over hard streets', 'observational cool, head-nod introspection']::TEXT[],
  ARRAY['project-window night air', 'tape-saturated closeness']::TEXT[],
  ARRAY['trap hats', '808 slides', 'shiny synths', 'stadium reverb']::TEXT[],
  ARRAY['dusty 90s Queensbridge boom bap', 'jazz-loop golden era hip hop']::TEXT[],
  2),
('Nas',
  'Stillmatic / God''s Son era (2001-2004)',
  2001,
  2004,
  'Queens, New York',
  90,
  100,
  'E minor',
  'mature east coast rap, cinematic and prophetic',
  ARRAY['snare hits bigger and rounder than the 90s break, studio-thick', 'kick doubled for weight, landing with authority', 'tambourine-shake texture riding the hats']::TEXT[],
  ARRAY['full low-end bed, produced and even', 'bass follows the chord root in long sustained pulls']::TEXT[],
  ARRAY['dramatic minor-key string section swells and cuts', 'choir-pad shimmer under the hook', 'lone church-organ chord held like a warning']::TEXT[],
  ARRAY['verses stripped, hooks open into full instrumentation', 'beat switches mood between verse and chorus']::TEXT[],
  ARRAY['elder-statesman gravity, righteous anger controlled', 'prophetic weight, every bar a verdict']::TEXT[],
  ARRAY['cathedral-sized hook space', 'tight dry verse pocket']::TEXT[],
  ARRAY['mumbled vocals', 'trap hats', 'autotune']::TEXT[],
  ARRAY['cinematic 2000s east coast rap', 'prophetic street sermon hip hop']::TEXT[],
  3),
('Kanye West',
  'College Dropout era (2003-2005)',
  2003,
  2005,
  'Chicago',
  84,
  96,
  'B-flat major',
  'sped-up soul-sample hip hop, triumphant and humane',
  ARRAY['snare snaps bright with a short clap layered on top', 'kick bumps rounded and even, pocketed under the sample', 'hats swung lightly, live-feel push and pull']::TEXT[],
  ARRAY['bassline plucks along with the sample chords, melodic and buoyant', 'low end rounded, never distorted']::TEXT[],
  ARRAY['pitched-up soul vocal chop carrying the hook melody', 'gospel piano chords stabbing on the downbeat', 'string flourish answering the vocal sample']::TEXT[],
  ARRAY['sample chopped and rearranged into new chord movement', 'gospel choir swell lifting the final chorus']::TEXT[],
  ARRAY['triumphant underdog joy', 'church-service lift with wit and hunger']::TEXT[],
  ARRAY['congregation-sized chorus space', 'crate-dust intimacy on verses']::TEXT[],
  ARRAY['dark ambience', '808 slides', 'whispered vocals']::TEXT[],
  ARRAY['chipmunk soul-sample hip hop', 'early-2000s Chicago gospel-lift rap']::TEXT[],
  4),
('Kanye West',
  'Yeezus era (2013-2014)',
  2013,
  2014,
  'Chicago',
  110,
  140,
  'C minor',
  'industrial minimalist rap, abrasive and confrontational',
  ARRAY['drums hit like machinery, clipped and distorted at the edges', 'kick punches through red-lined and square', 'silence used as percussion between slams']::TEXT[],
  ARRAY['distorted sub growl saturating the floor', 'bass arrives in violent bursts, then vanishes']::TEXT[],
  ARRAY['acid-line synth screech bent out of tune', 'single alarm-tone stab repeated without mercy', 'pitched scream sample used as an instrument']::TEXT[],
  ARRAY['brutal minimalism, two or three elements maximum', 'sudden full-stop breakdowns into unrelated texture']::TEXT[],
  ARRAY['confrontational art-rage', 'cold industrial menace with god-complex swagger']::TEXT[],
  ARRAY['concrete factory floor', 'signal-clipped airless mix']::TEXT[],
  ARRAY['soul samples', 'lush pads', 'polished mixing', 'melodic hooks']::TEXT[],
  ARRAY['industrial minimalist rap', 'distorted punk-energy hip hop']::TEXT[],
  5),
('Future',
  'Dirty Sprite / DS2 era (2014-2016)',
  2014,
  2016,
  'Atlanta',
  128,
  150,
  'F minor',
  'murky codeine trap, numb luxury and pain',
  ARRAY['hats stutter in double-time bursts then smear into rolls', 'snare lands late and lazy, dragging the pocket', 'kick tucked deep under the sub, felt not heard']::TEXT[],
  ARRAY['808 sustains long and syrup-thick, notes bending downward', 'sub floods the floor of the mix, murky and enveloping']::TEXT[],
  ARRAY['underwater synth pad wobbling slightly out of focus', 'minor-key bell line dripping in slow motion', 'detuned flute-like whistle drifting over the murk']::TEXT[],
  ARRAY['elements fade in and out of the haze rather than start and stop', 'hook and verse share one continuous gray mood']::TEXT[],
  ARRAY['numb opulent melancholy', 'toxic swagger dissolving into confession']::TEXT[],
  ARRAY['smoke-filled studio at 4am', 'mix submerged a foot underwater']::TEXT[],
  ARRAY['bright major chords', 'clean vocals', 'acoustic instruments']::TEXT[],
  ARRAY['murky Atlanta codeine trap', 'mid-2010s syrup-slow autotune melody']::TEXT[],
  6),
('Travis Scott',
  'Rodeo era (2014-2016)',
  2014,
  2016,
  'Houston',
  130,
  150,
  'G minor',
  'psychedelic dark trap, cinematic chaos',
  ARRAY['drums enter mid-song like a second act, sudden and huge', 'hats pan and flutter across the stereo field', 'snare drenched in gated reverb, hitting like a door slam']::TEXT[],
  ARRAY['808 distorted at the tip, growling on note changes', 'sub drops arrive as physical events, floor-shaking']::TEXT[],
  ARRAY['reversed synth swell blooming before each downbeat', 'haunted vocal chop pitched down into the shadows', 'guitar-shaped drone bent through heavy effects']::TEXT[],
  ARRAY['multi-part suite structure, beat morphs mid-track', 'long atmospheric intro before the drums land']::TEXT[],
  ARRAY['nocturnal amusement-park dread', 'controlled chaos, ecstatic and sinister at once']::TEXT[],
  ARRAY['endless dark arena', 'reverb tails stretching into black']::TEXT[],
  ARRAY['dry mixes', 'boom bap drums', 'happy chords']::TEXT[],
  ARRAY['psychedelic dark Houston trap', 'cinematic autotune haze']::TEXT[],
  7),
('Travis Scott',
  'Astroworld era (2018-2019)',
  2018,
  2019,
  'Houston',
  125,
  150,
  'A minor',
  'hazy carnival psychedelia, blockbuster trap',
  ARRAY['drums cleaner and rounder than the mixtape years, arena-ready', 'hat patterns morph every eight bars, restless', 'percussion drops to nothing for whole sections']::TEXT[],
  ARRAY['808 glides smooth and melodic, mixed glassy', 'sub full-blooded and wide, hugging the stereo edges']::TEXT[],
  ARRAY['carousel synth melody spinning slightly detuned', 'plucked psychedelic arp glittering overhead', 'pitched choir-pad rising like fairground lights']::TEXT[],
  ARRAY['beat switch as centerpiece, two songs stitched seamlessly', 'guest textures float in for one section then vanish']::TEXT[],
  ARRAY['wide-eyed nocturnal wonder', 'theme-park euphoria with an undertow of dread']::TEXT[],
  ARRAY['open-air festival night sky', 'chrome-smooth wide mix']::TEXT[],
  ARRAY['lo-fi grit', 'dusty samples', 'dry vocals']::TEXT[],
  ARRAY['hazy carnival psychedelic trap', 'stadium-scale autotune melody']::TEXT[],
  8),
('Kendrick Lamar',
  'good kid, m.A.A.d city era (2012-2013)',
  2012,
  2013,
  'Compton, Los Angeles',
  88,
  104,
  'E-flat minor',
  'cinematic west coast narrative rap',
  ARRAY['snare snaps tight and close, west coast crisp', 'kick hangs low-slung behind the beat', 'sparse percussion leaves room for the story']::TEXT[],
  ARRAY['rubbery synth bass rolls smooth under the verse', 'low end clean and even, never overwhelming the vocal']::TEXT[],
  ARRAY['night-drive electric piano shimmering in minor sevenths', 'thin g-funk whistle ghosting high above', 'moody pad drifting like marine layer fog']::TEXT[],
  ARRAY['beat morphs with the narrative, scene changes mid-song', 'ambient street-noise interludes stitch sections']::TEXT[],
  ARRAY['tense hometown nostalgia', 'quiet dread under youthful energy']::TEXT[],
  ARRAY['car interior at night', 'wide Compton boulevard air']::TEXT[],
  ARRAY['east coast boom bap drums', 'maximal EDM drops']::TEXT[],
  ARRAY['cinematic Compton narrative rap', 'moody west coast night-drive']::TEXT[],
  9),
('Kendrick Lamar',
  'To Pimp a Butterfly era (2015-2016)',
  2015,
  2016,
  'Los Angeles',
  80,
  110,
  'F minor',
  'live-band jazz-inflected protest rap',
  ARRAY['live drum kit played loose and human, ghost notes everywhere', 'snare tuned high and tight, jazz-kit crack', 'kick dances around the one instead of sitting on it']::TEXT[],
  ARRAY['thick fingered electric bass slides and pops, front and center', 'bassline improvises countermelody, alive and restless']::TEXT[],
  ARRAY['saxophone-shaped lead squalls at the edges of the mix', 'dense jazz-voiced keyboard stabs in odd clusters', 'vocal-chorus chants layered like a street rally']::TEXT[],
  ARRAY['band arrangement mutates every eight bars, through-composed', 'spoken-word passages over free-time backing']::TEXT[],
  ARRAY['righteous fury braided with celebration', 'sweat-and-genius live-room intensity']::TEXT[],
  ARRAY['cramped live room, mics bleeding into each other', 'stage-floor immediacy']::TEXT[],
  ARRAY['programmed trap drums', '808 slides', 'autotune', 'quantized grid feel']::TEXT[],
  ARRAY['live-band jazz-rooted protest rap', 'west coast free-jazz hip hop fusion']::TEXT[],
  10),
('J. Cole',
  '2014 Forest Hills Drive era (2014-2016)',
  2014,
  2016,
  'Fayetteville, North Carolina',
  84,
  98,
  'D minor',
  'introspective chopped-soul rap, self-produced intimacy',
  ARRAY['snare hits mid-soft with felt-mallet roundness', 'kick pattern simple and steady, serving the words', 'hats barely there, brushed and unhurried']::TEXT[],
  ARRAY['bass hums low and even like a porch-light drone', 'low end mixed modestly, vocal always on top']::TEXT[],
  ARRAY['faded soul-sample vocal sighing under the verse', 'lone piano figure repeating like a memory', 'thin string line rising only at emotional peaks']::TEXT[],
  ARRAY['long verses, minimal hooks, structure serves the storytelling', 'outro sections that dissolve into reflection']::TEXT[],
  ARRAY['confessional late-night honesty', 'hometown melancholy with earned hope']::TEXT[],
  ARRAY['childhood bedroom closeness', 'soft attic-studio air']::TEXT[],
  ARRAY['party energy', 'maximal drops', 'bright club synths']::TEXT[],
  ARRAY['introspective chopped-soul rap', 'confessional storytelling hip hop']::TEXT[],
  11),
('Drake',
  'Take Care era (2011-2012)',
  2011,
  2012,
  'Toronto',
  70,
  90,
  'B minor',
  'ambient nocturnal rap-R&B, muffled heartbreak luxury',
  ARRAY['drums muffled as if heard through a wall, soft-focus', 'snare padded and low-passed, landing like a heartbeat', 'sparse finger-snap textures where hats would be']::TEXT[],
  ARRAY['sub swells slow beneath layers of pad, felt as pressure', 'bass notes long and mournful, moving in whole bars']::TEXT[],
  ARRAY['submerged R&B vocal sample pitched down into the dark', 'electric piano chords blurred with tape wobble', 'synth pad like city lights through rain on glass']::TEXT[],
  ARRAY['songs drift between rap and sung sections without seams', 'space and silence carry the emotional weight']::TEXT[],
  ARRAY['champagne melancholy at 3am', 'guarded vulnerability, luxury with the lights off']::TEXT[],
  ARRAY['penthouse window overlooking cold city', 'cavernous muffled distance']::TEXT[],
  ARRAY['aggressive drums', 'distortion', 'bright energy']::TEXT[],
  ARRAY['ambient Toronto night R&B rap', 'muffled nocturnal heartbreak luxury']::TEXT[],
  12),
('Drake',
  'If You''re Reading This era (2015-2016)',
  2015,
  2016,
  'Toronto',
  120,
  144,
  'C-sharp minor',
  'icy sparse trap, cold-shoulder confidence',
  ARRAY['hats pattern sparse and icy with sudden double-time stutters', 'snare cracks solitary in empty space', 'drums enter late, letting the loop set the menace first']::TEXT[],
  ARRAY['808 hits chosen and placed, not rolled — each one deliberate', 'sub cold and dry, no distortion, pure pressure']::TEXT[],
  ARRAY['frozen music-box melody repeating unbothered', 'gray synth pad hanging motionless', 'pitch-warped vocal fragment echoing once then gone']::TEXT[],
  ARRAY['ruthless minimalism, three elements and a voice', 'no hook resolution, tension never released']::TEXT[],
  ARRAY['paranoid victory-lap coldness', 'six-god detachment, threats delivered flat']::TEXT[],
  ARRAY['empty mansion at 4am', 'dead winter air, zero reverb']::TEXT[],
  ARRAY['lush chords', 'sung hooks', 'soul samples']::TEXT[],
  ARRAY['icy sparse Toronto trap', 'cold minimal menace rap']::TEXT[],
  13),
('21 Savage',
  'Savage Mode era (2016-2017)',
  2016,
  2017,
  'Atlanta',
  120,
  140,
  'D minor',
  'whispered horror-minimal trap',
  ARRAY['hats whisper in slow triplets, patient and unhurried', 'snare flat and executioner-dry on the three', 'kick minimal, letting dread fill the gaps']::TEXT[],
  ARRAY['808 tuned low and hollow, tolling like a bell in a basement', 'sub lurks rather than drives, arriving in slow pulses']::TEXT[],
  ARRAY['horror-film music-box chime circling one phrase', 'detuned whistle drifting like wind through a door crack', 'single string note sustained to the point of discomfort']::TEXT[],
  ARRAY['nothing enters, nothing leaves — static dread loop', 'texture shifts happen underneath, almost subliminal']::TEXT[],
  ARRAY['dead-eyed quiet menace', 'violence described at a whisper']::TEXT[],
  ARRAY['abandoned house interior', 'flat airless closeness']::TEXT[],
  ARRAY['energetic drums', 'bright melody', 'big hooks', 'major keys']::TEXT[],
  ARRAY['whispered horror-minimal Atlanta trap', 'slow dead-eyed menace']::TEXT[],
  14),
('Metro Boomin',
  'Peak run era (2015-2018)',
  2015,
  2018,
  'Atlanta via St. Louis',
  128,
  150,
  'C-sharp minor',
  'cinematic villain trap, orchestral dread meets 808 physics',
  ARRAY['hats roll in precise bursts, machine-tight then silent', 'snare layered with a whip-crack transient, mixed loud', 'kick and 808 fused into one seismic hit']::TEXT[],
  ARRAY['808 tuned melodic, gliding between root and fifth', 'sub mixed enormous, the physical center of the record']::TEXT[],
  ARRAY['gothic bell theme tolling a minor arpeggio', 'ghost-choir pad breathing under the melody', 'lone cinematic string line sawing with dread']::TEXT[],
  ARRAY['grand intro theme, then the drop recontextualizes it', 'arrangement subtracts to pure 808 and voice for verses']::TEXT[],
  ARRAY['supervillain grandeur', 'luxurious doom, immaculate and heavy']::TEXT[],
  ARRAY['marble hall reverb on melody, dead-dry drums', 'IMAX-scale depth of field']::TEXT[],
  ARRAY['live drums', 'lo-fi texture', 'happy melody']::TEXT[],
  ARRAY['cinematic villain trap', 'orchestral-dread 808 production']::TEXT[],
  15),
('Playboi Carti',
  'Whole Lotta Red era (2020-2021)',
  2020,
  2021,
  'Atlanta',
  145,
  170,
  'A minor',
  'rage rap, distorted synth-punk trap',
  ARRAY['kick pattern pogos in relentless four-bar loops', 'snare buried under synth distortion, more felt than heard', 'hats optional — the synth carries the rhythm']::TEXT[],
  ARRAY['808 bit-crushed and square, buzzing at the edge of blowout', 'low end fused with the synth into one wall of pressure']::TEXT[],
  ARRAY['sawtooth synth riff screaming in a two-bar cycle', 'video-nasty arpeggio strobing red and black', 'baby-voice vocal chirps used as percussion']::TEXT[],
  ARRAY['no build, no break — full intensity from bar one', 'track ends abruptly like a power cut']::TEXT[],
  ARRAY['mosh-pit vampire mania', 'ecstatic destructive abandon']::TEXT[],
  ARRAY['strobe-lit basement show', 'red-lined and claustrophobic']::TEXT[],
  ARRAY['soul samples', 'clean mixing', 'slow tempo', 'acoustic texture']::TEXT[],
  ARRAY['distorted rage-rap synth punk', 'strobing mosh-pit trap']::TEXT[],
  16),
('Gunna',
  'Drip Season era (2017-2019)',
  2017,
  2019,
  'Atlanta',
  130,
  150,
  'E minor',
  'liquid melodic trap, effortless designer glide',
  ARRAY['hats flow in smooth continuous streams, never harsh', 'snare soft-tipped, gliding into place rather than hitting', 'percussion mixed silky, everything rounded off']::TEXT[],
  ARRAY['808 slides long and legato, melodic as a bassline', 'sub smooth and buttery, weight without aggression']::TEXT[],
  ARRAY['breathy flute melody curling like smoke', 'harp-pluck arpeggio cascading downward', 'watery synth keys rippling in the background']::TEXT[],
  ARRAY['seamless loop luxury, changes felt as texture not events', 'melody and flow interlock in one continuous stream']::TEXT[],
  ARRAY['weightless designer nonchalance', 'sunlit infinity-pool calm with money confidence']::TEXT[],
  ARRAY['glass villa openness', 'soft-focus expensive air']::TEXT[],
  ARRAY['hard aggression', 'distortion', 'dusty samples']::TEXT[],
  ARRAY['liquid melodic Atlanta trap', 'silk-glide designer flow']::TEXT[],
  17),
('Lil Wayne',
  'Tha Carter II era (2005-2007)',
  2005,
  2007,
  'New Orleans',
  84,
  100,
  'G minor',
  'southern bounce lineage mixtape-run fire, martian charisma',
  ARRAY['snare rolls stutter in southern double-hits', 'kick bounces syncopated, second-line lineage in the pattern', 'hi-hat opens on the offbeat like a hiss of steam']::TEXT[],
  ARRAY['bass thick and rounded, bouncing with the kick pattern', 'low end pushes forward, driving not dragging']::TEXT[],
  ARRAY['triumphant synth-string fanfare stabs', 'greasy pocket groove guitar lick cycling under the verse', 'gliding whistle-synth answering the vocal']::TEXT[],
  ARRAY['beat leaves gaps for ad-libs and lighter flicks', 'hook hits big then drops back to raw verse energy']::TEXT[],
  ARRAY['best-rapper-alive mixtape hunger', 'grinning menace, punchlines thrown like dice']::TEXT[],
  ARRAY['candy-painted car cabin', 'humid southern night air']::TEXT[],
  ARRAY['east coast boom bap drums', 'moody ambience']::TEXT[],
  ARRAY['mid-2000s southern bounce-lineage rap', 'mixtape-run fire flow']::TEXT[],
  18),
('Jay-Z',
  'The Blueprint era (2001-2003)',
  2001,
  2003,
  'Brooklyn, New York',
  88,
  98,
  'A-flat major',
  'stately soul-sample rap, executive triumph',
  ARRAY['snare thick and regal, sitting exactly on the grid', 'kick full-bodied, mixed like a heartbeat under silk', 'minimal hat work, the sample carries the motion']::TEXT[],
  ARRAY['bassline borrowed from the soul record, walking with dignity', 'low end rich and unhurried, tailored not tuned']::TEXT[],
  ARRAY['sped-up soul diva vocal wailing the hook line', 'stately piano-and-strings figure from the source record', 'organ swell rising under the final verses']::TEXT[],
  ARRAY['sample rides whole, chopped only at the seams', 'arrangement opens wider verse by verse like a coronation']::TEXT[],
  ARRAY['CEO-calm dominance', 'victory-lap elegance, effortless finality']::TEXT[],
  ARRAY['mahogany boardroom acoustics', 'vintage console glue']::TEXT[],
  ARRAY['trap hats', 'synth leads', 'distortion']::TEXT[],
  ARRAY['stately soul-sample rap', 'executive-triumph east coast hip hop']::TEXT[],
  19),
('Mobb Deep',
  'The Infamous era (1995-1996)',
  1995,
  1996,
  'Queensbridge, New York',
  84,
  94,
  'B-flat minor',
  'cold gray Queensbridge menace, winter in mono',
  ARRAY['snare like a slammed metal door, short and final', 'kick muffled and heavy as boots on wet pavement', 'drums swung slightly drunk, dragging with intent']::TEXT[],
  ARRAY['bass murmurs low and ominous in single held notes', 'low end damp and concrete-gray, never round']::TEXT[],
  ARRAY['dissonant piano cluster ringing like a broken payphone', 'ghostly string smear hanging in the cold', 'reversed texture creeping under the loop']::TEXT[],
  ARRAY['loop unchanging as a stakeout, tension by attrition', 'stripped chorus — same beat, colder vocals']::TEXT[],
  ARRAY['shivering project-hallway dread', 'calm articulate hostility']::TEXT[],
  ARRAY['stairwell echo in mono', 'February air inside the mix']::TEXT[],
  ARRAY['bright samples', 'major chords', 'party drums', 'melodic hooks']::TEXT[],
  ARRAY['cold Queensbridge menace boom bap', 'gray winter mono street rap']::TEXT[],
  20),
('Three 6 Mafia',
  'Mystic Stylez era (1995-1997)',
  1995,
  1997,
  'Memphis',
  128,
  144,
  'F minor',
  'occult lo-fi Memphis horrorcore',
  ARRAY['drum machine hits boxy and cheap, saturated by cassette dub', 'hats double-time in hissing bursts', 'snare dry as bone, pushed slightly early']::TEXT[],
  ARRAY['808 boom overdriven into the tape, edges furred', 'low end rumbles constant like an idling engine']::TEXT[],
  ARRAY['evil detuned bell theme circling like a ritual', 'shrieking string sample looped into a drone', 'pitch-black organ tone humming beneath']::TEXT[],
  ARRAY['chant-hook repetition as incantation', 'verses trade fast over the unblinking loop']::TEXT[],
  ARRAY['seance-basement malice', 'trance-tight ritual aggression']::TEXT[],
  ARRAY['tape-hiss basement haze', 'lo-fi fourth-generation dub murk']::TEXT[],
  ARRAY['clean mixing', 'live instruments', 'bright synths', 'major keys']::TEXT[],
  ARRAY['occult lo-fi Memphis horrorcore', 'cassette-dub devil-drone rap']::TEXT[],
  21),
('UGK',
  'Ridin'' Dirty era (1996-1998)',
  1996,
  1998,
  'Port Arthur, Texas',
  80,
  96,
  'E-flat major',
  'Texas slab music, live-feel country-rap cadillac glide',
  ARRAY['drums pocketed deep and lazy, played not programmed', 'snare fat with a live-room ring left in', 'kick rolls with the bassline like wheels on asphalt']::TEXT[],
  ARRAY['live electric bass sliding greasy between chord tones', 'low end round and road-trip steady, trunk pressure without distortion']::TEXT[],
  ARRAY['blues guitar lick bending slow in the heat', 'church-organ pad sustaining under the hook', 'silky backing-vocal harmonies drifting in']::TEXT[],
  ARRAY['band-feel arrangement, instruments trade fills', 'long instrumental outro riding into the sunset']::TEXT[],
  ARRAY['candy-paint sunset cruise confidence', 'country-boy game told smooth and unhurried']::TEXT[],
  ARRAY['open highway heat shimmer', 'leather-interior closeness']::TEXT[],
  ARRAY['programmed trap drums', 'synthetic textures', 'east coast grit']::TEXT[],
  ARRAY['Texas slab-music country rap', 'live-feel cadillac glide']::TEXT[],
  22),
('OutKast',
  'ATLiens era (1996-1998)',
  1996,
  1998,
  'Atlanta',
  82,
  94,
  'D minor',
  'interstellar southern soul, spaced-out dungeon wisdom',
  ARRAY['drums thump soft and subterranean, dungeon-damp', 'snare brushed with dust, landing slightly behind', 'shaker pulse hissing like night insects']::TEXT[],
  ARRAY['deep melodic bassline prowling in slow arcs', 'sub tuned low and meditative, cave-floor steady']::TEXT[],
  ARRAY['alien pad shimmering like heat off a UFO hull', 'echo-soaked guitar chop floating in orbit', 'spectral choir hum threading the hook']::TEXT[],
  ARRAY['space between elements as wide as the message', 'hooks sung half-whispered over the emptiness']::TEXT[],
  ARRAY['extraterrestrial southern calm', 'prophetic front-porch wisdom after midnight']::TEXT[],
  ARRAY['red-clay basement with the lights off', 'orbit-wide stereo field']::TEXT[],
  ARRAY['NY boom bap bounce', 'aggressive drums', 'bright pop synths']::TEXT[],
  ARRAY['interstellar southern soul rap', 'spaced-out dungeon hip hop']::TEXT[],
  23),
('50 Cent',
  'Get Rich or Die Tryin'' era (2003-2005)',
  2003,
  2005,
  'Queens, New York',
  90,
  102,
  'C minor',
  'bulletproof G-Unit bounce, menace you can dance to',
  ARRAY['snare cracks huge and gated, mixed for club walls', 'kick pattern bounces gym-strong and simple', 'synthetic hat pattern ticking precise as a timer']::TEXT[],
  ARRAY['bass punches in short muscular hits with the kick', 'low end tight and dry, built for impact not sustain']::TEXT[],
  ARRAY['ominous synth-string vamp circling two chords', 'g-funk-descended whistle lead grinning over the menace', 'staccato piano jabs marking the bar line']::TEXT[],
  ARRAY['four-bar loop discipline, hook engineered for chanting', 'drops built around the sung-threat chorus']::TEXT[],
  ARRAY['smiling invincible menace', 'club-ready gangster swagger, playful and lethal']::TEXT[],
  ARRAY['armored-truck interior tightness', 'club main-room punch']::TEXT[],
  ARRAY['dusty lo-fi texture', 'live drums', 'melancholy ambience']::TEXT[],
  ARRAY['early-2000s G-Unit gangster bounce', 'club-menace east coast rap']::TEXT[],
  24),
('Pusha T',
  'Daytona era (2018-2019)',
  2018,
  2019,
  'Virginia',
  86,
  98,
  'B-flat minor',
  'luxury-loop coke rap, surgical minimalism',
  ARRAY['drums arrive sparse and off-kilter, drum-break shrapnel', 'snare placed a hair late, arrogant in its lateness', 'kick pattern irregular, punching through loop seams']::TEXT[],
  ARRAY['bass smeared from the sample, low and grimy-elegant', 'sub reinforcement surgical, only where the loop dips']::TEXT[],
  ARRAY['exotic psych-rock sample flipped into a sneer', 'detuned vocal fragment cycling like a curse', 'single filthy keyboard riff looped without apology']::TEXT[],
  ARRAY['loop flips mid-verse as the only event, maximal restraint', 'no choruses wasted — beat change as punctuation']::TEXT[],
  ARRAY['kingpin disdain, immaculate and unbothered', 'museum-quality menace']::TEXT[],
  ARRAY['marble penthouse dryness', 'sample dust under glass']::TEXT[],
  ARRAY['melodic autotune', 'trap hat rolls', 'pop hooks', 'lush pads']::TEXT[],
  ARRAY['luxury-loop coke rap', 'surgical minimalist sample flip']::TEXT[],
  25)
ON CONFLICT (artist_name, era_label) DO UPDATE SET
  era_start = EXCLUDED.era_start,
  era_end = EXCLUDED.era_end,
  region = EXCLUDED.region,
  bpm_min = EXCLUDED.bpm_min,
  bpm_max = EXCLUDED.bpm_max,
  key_preference = EXCLUDED.key_preference,
  feel = EXCLUDED.feel,
  percussion_dna = EXCLUDED.percussion_dna,
  low_end_dna = EXCLUDED.low_end_dna,
  lead_dna = EXCLUDED.lead_dna,
  arrangement_dna = EXCLUDED.arrangement_dna,
  energy_dna = EXCLUDED.energy_dna,
  room_dna = EXCLUDED.room_dna,
  avoid_list = EXCLUDED.avoid_list,
  anchor_tokens = EXCLUDED.anchor_tokens,
  display_order = EXCLUDED.display_order,
  updated_at = NOW();
